GRANT USAGE ON SCHEMA cultivo TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cultivo TO postgres;

GRANT USAGE ON SCHEMA finca TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA finca TO postgres;

GRANT USAGE ON SCHEMA sensores TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sensores TO postgres;

GRANT USAGE ON SCHEMA usuario TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA usuario TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA cultivo GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA finca GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA sensores GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA usuario GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO postgres;