appname = API_CRUD_FINCA
httpport = 8086
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:sistem@127.0.0.1/SPIKE?sslmode=disable&search_path=finca
